name: checkout workflow
on: [push, pull_request]

jobs:
  check-sha-ref:
    runs-on: ubuntu-latest
    steps:
      - name: check current branch
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
