name: checkout workflow
on: [push, pull_request]

jobs:
  checkout-list-files:
    runs-on: ubuntu-latest
    steps:
      - name: list before checkout
        run: ls -a
      - name: checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main

      - name: list after checkout
        run: ls -a
